'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
'
Namespace AlisServices
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SecurityUserServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SecurityUserService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private FetchUserByIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FetchUserByUserNameOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ValidatePasswordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SMSAutoRenewManager.My.MySettings.Default.SMSAutoRenewManager_AlisServices_SecurityUserService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event FetchUserByIdCompleted As FetchUserByIdCompletedEventHandler
        
        '''<remarks/>
        Public Event FetchUserByUserNameCompleted As FetchUserByUserNameCompletedEventHandler
        
        '''<remarks/>
        Public Event ValidatePasswordCompleted As ValidatePasswordCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchUserById", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FetchUserById(ByVal alisUserID As Integer) As AlisSecurityUser
            Dim results() As Object = Me.Invoke("FetchUserById", New Object() {alisUserID})
            Return CType(results(0),AlisSecurityUser)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FetchUserByIdAsync(ByVal alisUserID As Integer)
            Me.FetchUserByIdAsync(alisUserID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FetchUserByIdAsync(ByVal alisUserID As Integer, ByVal userState As Object)
            If (Me.FetchUserByIdOperationCompleted Is Nothing) Then
                Me.FetchUserByIdOperationCompleted = AddressOf Me.OnFetchUserByIdOperationCompleted
            End If
            Me.InvokeAsync("FetchUserById", New Object() {alisUserID}, Me.FetchUserByIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnFetchUserByIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.FetchUserByIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FetchUserByIdCompleted(Me, New FetchUserByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchUserByUserName", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FetchUserByUserName(ByVal alisUserName As String) As AlisSecurityUser
            Dim results() As Object = Me.Invoke("FetchUserByUserName", New Object() {alisUserName})
            Return CType(results(0),AlisSecurityUser)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FetchUserByUserNameAsync(ByVal alisUserName As String)
            Me.FetchUserByUserNameAsync(alisUserName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FetchUserByUserNameAsync(ByVal alisUserName As String, ByVal userState As Object)
            If (Me.FetchUserByUserNameOperationCompleted Is Nothing) Then
                Me.FetchUserByUserNameOperationCompleted = AddressOf Me.OnFetchUserByUserNameOperationCompleted
            End If
            Me.InvokeAsync("FetchUserByUserName", New Object() {alisUserName}, Me.FetchUserByUserNameOperationCompleted, userState)
        End Sub
        
        Private Sub OnFetchUserByUserNameOperationCompleted(ByVal arg As Object)
            If (Not (Me.FetchUserByUserNameCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FetchUserByUserNameCompleted(Me, New FetchUserByUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidatePassword", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ValidatePassword(ByVal alisUserName As String, ByVal password As String) As Object
            Dim results() As Object = Me.Invoke("ValidatePassword", New Object() {alisUserName, password})
            Return CType(results(0),Object)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ValidatePasswordAsync(ByVal alisUserName As String, ByVal password As String)
            Me.ValidatePasswordAsync(alisUserName, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ValidatePasswordAsync(ByVal alisUserName As String, ByVal password As String, ByVal userState As Object)
            If (Me.ValidatePasswordOperationCompleted Is Nothing) Then
                Me.ValidatePasswordOperationCompleted = AddressOf Me.OnValidatePasswordOperationCompleted
            End If
            Me.InvokeAsync("ValidatePassword", New Object() {alisUserName, password}, Me.ValidatePasswordOperationCompleted, userState)
        End Sub
        
        Private Sub OnValidatePasswordOperationCompleted(ByVal arg As Object)
            If (Not (Me.ValidatePasswordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ValidatePasswordCompleted(Me, New ValidatePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AlisSecurityUser
        
        Private userNameField As String
        
        Private userIDField As Integer
        
        Private firstNameField As String
        
        Private lastNameField As String
        
        Private securityRightsField() As SecurityRight
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserID() As Integer
            Get
                Return Me.userIDField
            End Get
            Set
                Me.userIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecurityRights() As SecurityRight()
            Get
                Return Me.securityRightsField
            End Get
            Set
                Me.securityRightsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SecurityRight
        
        Private nameField As String
        
        Private securityRightIDField As Integer
        
        Private pathField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecurityRightID() As Integer
            Get
                Return Me.securityRightIDField
            End Get
            Set
                Me.securityRightIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Path() As String
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub FetchUserByIdCompletedEventHandler(ByVal sender As Object, ByVal e As FetchUserByIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FetchUserByIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AlisSecurityUser
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AlisSecurityUser)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub FetchUserByUserNameCompletedEventHandler(ByVal sender As Object, ByVal e As FetchUserByUserNameCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FetchUserByUserNameCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AlisSecurityUser
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AlisSecurityUser)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub ValidatePasswordCompletedEventHandler(ByVal sender As Object, ByVal e As ValidatePasswordCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ValidatePasswordCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object)
            End Get
        End Property
    End Class
End Namespace
